### PR TITLE
Adding the NANOG88 Video Recording 

### PR DESCRIPTION
**Pull request by tking**
Added the NANOG88 video recording

### CODE REVIEW

**Comment by tking** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by grizz — APPROVED** [review]

**Comment by grizz** [comment]
recheck

**Comment by tking** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by tking — COMMENTED** [review]
I have read the CLA Document and I hereby sign the CLA

**Comment by tking** [comment]
recheck

**Review by grizz — APPROVED** [review]

**Comment by grizz** [comment]
recheck

**Comment by grizz** [comment]
@tking I broken the CLA when I added branch protection, I think I have it fixed now, but you might need to sign again.

**Comment by grizz** [comment]
recheck

**Pull request merged**
